name: Get Current Pull Request
description: Get Current Pull Request URL & Title
author: everpcpc

inputs:
  token:
    description: GitHub Token
    required: true

outputs:
  url:
    description: HTML url for pull request
  title:
    description: Pull request title
  author:
    description: Author name for pull request

runs:
  using: node16
  main: dist/index.js

branding:
  icon: message-circle
  color: green
